-- ==============================================================================
-- SALIMNA PLATFORM - SUPABASE DATABASE SCHEMA & SEED DATA
-- ==============================================================================
-- Petunjuk Penggunaan:
-- 1. Buka dashboard Supabase Anda di https://supabase.com/dashboard
-- 2. Pilih Project Anda -> Buka menu "SQL Editor" di bilah samping kiri
-- 3. Buat "New Query", tempel (paste) seluruh isi file ini, lalu klik "Run"
-- ==============================================================================

-- 1. TABEL PRODUCTS (Produk & Pakaian Salimna Cloth)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  price BIGINT NOT NULL,
  price_formatted TEXT NOT NULL,
  category TEXT NOT NULL,
  images JSONB NOT NULL DEFAULT '[]'::jsonb,
  badge TEXT DEFAULT '',
  description TEXT DEFAULT '',
  buy_link TEXT DEFAULT '',
  stock INTEGER DEFAULT 10,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABEL ARTICLES (Artikel, Riset & Pemikiran Salimna)
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL,
  description TEXT NOT NULL,
  content TEXT NOT NULL,
  image TEXT NOT NULL,
  author TEXT DEFAULT 'Tim Riset Salimna',
  read_time TEXT DEFAULT '5 mnt',
  is_published INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABEL ORDERS (Pesanan & Checkout)
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_amount BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  whatsapp_status TEXT NOT NULL DEFAULT 'pending',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABEL INQUIRIES (Pesan Kontak & Pertanyaan Pengunjung)
CREATE TABLE IF NOT EXISTS public.inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- INDEXING UNTUK PERFORMA QUERY CEPAT
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products (slug);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (category);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON public.products (is_active);
CREATE INDEX IF NOT EXISTS idx_articles_slug ON public.articles (slug);
CREATE INDEX IF NOT EXISTS idx_articles_category ON public.articles (category);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders (order_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders (status);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Memungkinkan akses aman baik via Backend (Service Role / Anon Key) maupun Client
-- ==============================================================================
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Public can view products" ON public.products;
DROP POLICY IF EXISTS "Full access to products" ON public.products;
DROP POLICY IF EXISTS "Public can view articles" ON public.articles;
DROP POLICY IF EXISTS "Full access to articles" ON public.articles;
DROP POLICY IF EXISTS "Public can create orders" ON public.orders;
DROP POLICY IF EXISTS "Full access to orders" ON public.orders;
DROP POLICY IF EXISTS "Public can submit inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Full access to inquiries" ON public.inquiries;

-- Products Policies: Public read, full access for management
CREATE POLICY "Public can view products" ON public.products
  FOR SELECT USING (true);

CREATE POLICY "Full access to products" ON public.products
  FOR ALL USING (true) WITH CHECK (true);

-- Articles Policies: Public read, full access for management
CREATE POLICY "Public can view articles" ON public.articles
  FOR SELECT USING (true);

CREATE POLICY "Full access to articles" ON public.articles
  FOR ALL USING (true) WITH CHECK (true);

-- Orders Policies: Public create & read, full management access
CREATE POLICY "Public can create orders" ON public.orders
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Full access to orders" ON public.orders
  FOR ALL USING (true) WITH CHECK (true);

-- Inquiries Policies: Public submit inquiry
CREATE POLICY "Public can submit inquiries" ON public.inquiries
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Full access to inquiries" ON public.inquiries
  FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- SEED INITIAL DATA (Data Awal Produk & Artikel Salimna)
-- ==============================================================================

-- 1. Seed Produk
INSERT INTO public.products (name, slug, price, price_formatted, category, images, badge, description, buy_link, stock, is_active)
VALUES
  (
    'Revelation Shirt',
    'revelation-shirt',
    249000,
    'Rp 249.000',
    'Salimna Cloth',
    '[
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800&auto=format&fit=crop"
    ]'::jsonb,
    'Terlaris',
    'Baju lengan panjang katun premium kelas berat yang memadukan keindahan seni visual, kaligrafi Arab, dan pesan filosofis "Revelation: Light Over Darkness". Setiap helai kain menyiratkan perjalanan pengungkapan makna.',
    'https://wa.me/6282131653815',
    25,
    1
  ),
  (
    'Tee Light Over Darkness',
    'tee-light-over-darkness',
    199000,
    'Rp 199.000',
    'Edisi Terbatas',
    '[
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523381313430-8025287ade3b?q=80&w=800&auto=format&fit=crop"
    ]'::jsonb,
    'Baru',
    'Kaos katun combed 24s dengan sablon dada simbolis. Mencerminkan filosofi inti Salimna: mengungkap kebenaran melalui ketekunan dan refleksi.',
    'https://wa.me/6282131653815',
    30,
    1
  ),
  (
    'Hoodie Filosofi',
    'hoodie-filosofi',
    399000,
    'Rp 399.000',
    'Esensial',
    '[
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop"
    ]'::jsonb,
    'Eksklusif',
    'Hoodie hitam oversized 330 GSM dengan logo Salimna bordir presisi. Kain kelas berat untuk kenyamanan dan keawetan perjalanan kontemplasi Anda.',
    'https://wa.me/6282131653815',
    15,
    1
  ),
  (
    'Totebag Salimna',
    'totebag-salimna',
    89000,
    'Rp 89.000',
    'Aksesori',
    '[
      "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop"
    ]'::jsonb,
    '',
    'Totebag kanvas tebal ramah lingkungan untuk menemani membawa buku catatan dan bahan riset harian Anda.',
    'https://wa.me/6282131653815',
    40,
    1
  )
ON CONFLICT (slug) DO NOTHING;

-- 2. Seed Artikel
INSERT INTO public.articles (title, slug, category, date, description, content, image, author, read_time, is_published)
VALUES
  (
    'Pergeseran Altruisme Perkotaan di Abad ke-21',
    'pergeseran-altruisme-perkotaan',
    'Sosial',
    '24 Okt 2023',
    'Analisis tentang bagaimana konektivitas digital mengubah cara kita memandang dan mempraktikkan tanggung jawab sosial.',
    'Konektivitas digital telah mengubah lanskap interaksi manusia secara mendasar. Di lingkungan urban kontemporer, empati tidak lagi hanya terwujud dalam perjumpaan fisik, melainkan tersalurkan melalui jejaring komputasi. Fenomena ini menciptakan paradoks: di satu sisi, kepedulian dapat digerakkan dalam hitungan detik lintas benua; di sisi lain, kedalaman relasi emosional sering kali tereduksi menjadi sekadar gestur digital semu. Salimna meneliti bagaimana generasi muda menyikapi tantangan ini dengan merevitalisasi ruang-ruang komunal yang menggabungkan kesadaran spiritual dan tindakan nyata.',
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop',
    'Tim Riset Salimna',
    '6 mnt',
    1
  ),
  (
    'Pola yang Tak Terlihat: Geometri Suci pada Flora Lokal',
    'pola-geometri-suci-flora-lokal',
    'Alam',
    '02 Nov 2023',
    'Menjelajahi keindahan matematis dan simbolisme religius yang ditemukan dalam fenomena alam regional.',
    'Alam semesta berbicara dalam bahasa proporsi yang teratur. Dari filotaksis daun hingga spiralling biji bunga matahari, pola rasio emas (golden ratio) dan deret Fibonacci mengalir secara konsisten. Kajian kami terhadap keanekaragaman flora lokal di Nusantara mengungkap bagaimana masyarakat tradisional sejak lama telah menginternalisasi pola-pola sakral ini ke dalam motif kain, ukiran arsitektur, dan filosofi hidup selaras dengan alam semesta.',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    'Tim Riset Salimna',
    '5 mnt',
    1
  ),
  (
    'Asketisme Modern: Menemukan Keheningan di Dunia yang Bising',
    'asketisme-modern-keheningan',
    'Religius',
    '15 Des 2023',
    'Bagaimana praktik keagamaan tradisional diadaptasi oleh kaum muda untuk mengatasi kelelahan digital.',
    'Di tengah arus notifikasi tanpa henti dan kejenuhan informasi, praktik asketisme kuno menemukan relevansi baru. Bukan dalam bentuk pengasingan diri ke gua atau hutan, melainkan "digital fasting" dan perenungan hening terjadwal di tengah hiruk-pikuk kota. Riset kami mengamati bagaimana ritual zikir dan kontemplasi mendalam kini bertransformasi menjadi oase kesehatan mental bagi masyarakat modern yang merindukan kedamaian batin.',
    'https://images.unsplash.com/photo-1507692049790-de58290a4334?q=80&w=800&auto=format&fit=crop',
    'Tim Riset Salimna',
    '7 mnt',
    1
  ),
  (
    'Estetika Kegelapan dan Cahaya: Makna Filosofis Seri Revelation',
    'estetika-kegelapan-dan-cahaya-revelation',
    'Filosofi',
    '10 Jan 2024',
    'Kajian konseptual mengenai bagaimana pakaian dapat menjadi media dialog intelektual dan perwujudan pesan pencerahan.',
    'Seri "Revelation" dari Salimna Cloth bukan sekadar produk sandang, melainkan kanvas ideologis. Dengan tema "Light Over Darkness", desain kami menarasikan perjalanan manusia dari ketidaktahuan menuju kesadaran spiritual. Kami memadukan tipografi kontemporer dengan kaligrafi simbolik untuk mengingatkan pemakainya bahwa setiap kesulitan selalu memuat benih pencerahan.',
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop',
    'Tim Riset Salimna',
    '4 mnt',
    1
  )
ON CONFLICT (slug) DO NOTHING;

-- 3. Seed Sampel Pesanan
INSERT INTO public.orders (order_number, customer_name, customer_email, customer_phone, shipping_address, items, total_amount, status, notes)
VALUES
  (
    'SLM-2026-001',
    'Ahmad Fauzi',
    'fauzi@example.com',
    '081234567890',
    'Jl. Kebon Jeruk No. 12, Jakarta Barat',
    '[{"id": 1, "name": "Revelation Shirt", "size": "L", "qty": 1, "price": 249000}]'::jsonb,
    249000,
    'confirmed',
    'Mohon sertakan stiker Salimna'
  )
ON CONFLICT (order_number) DO NOTHING;
